# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  # stuff relating to the UI
  windowSize: full # one of 'normal' | 'half' | 'full' default is 'normal'
  # scrollHeight: 2 # how many lines you scroll by
  # scrollPastBottom: true # enable scrolling past the bottom
  # scrollOffMargin: 2 # how many lines to keep before/after the cursor when it reaches the top/bottom of the view; see 'Scroll-off Margin' section below
  # scrollOffBehavior: "margin" # one of 'margin' | 'jump'; see 'Scroll-off Margin' section below
  sidePanelWidth: 0.3 # number from 0 to 1
  expandFocusedSidePanel: true
  mainPanelSplitMode: flexible # one of 'horizontal' | 'flexible' | 'vertical'
  enlargedSideViewLocation: left # one of 'left' | 'top'
  # language: 'auto' # one of 'auto' | 'en' | 'zh-CN' | 'zh-TW' | 'pl' | 'nl' | 'ja' | 'ko' | 'ru'
  timeFormat: '2006-02-25' # https://pkg.go.dev/time#Time.Format
  shortTimeFormat: '15:04'
 
